POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Esta es una nueva nota",
  "important": true
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJlbml0byIsImlkIjoiNjUyNTdmNTIxNzBmNTlhOGI0OWI5Zjg0IiwiaWF0IjoxNjk3MjA2MTg5LCJleHAiOjE2OTcyMDk3ODl9.jVMLaU1B79WPseGt8C2Y1ObHGQL5-hS3dW1c7xoufrw

{
  "content": "Esta es una nota fantastica!!!!"
}